"""changes

Revision ID: 638b101f31eb
Revises: 9cea09b94356
Create Date: 2023-10-04 21:47:44.633008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638b101f31eb'
down_revision = '9cea09b94356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
